### ISSUE TITLE
无法解析竞技场对手属性

### ISSUE THREAD

**Issue by ShinodaKiyoshimo** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#106]
刷新竞技场之后是这个样子
![image](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/assets/87769282/501f410b-7074-41cb-aea5-180f37617995)

**Comment by EtherealAO** [comment]
经检查，日服已经修复了竞技场对手的属性会被下发的bug
