### ISSUE TITLE
JJC请求“解包失败”

### ISSUE THREAD

**Issue by Array-Cats** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#42]
参考作者在 #41 中的回答发出该issues，游戏打开后第一次进入JJC时程序弹出“解析Respones时出现错误”但没有显示JJC数据。

![lFT4C.png](https://s1.328888.xyz/2022/05/26/lFT4C.png)

**Comment by EtherealAO** [comment]
复现失败

**Comment by Array-Cats** [comment]
> 复现失败

并不是每次都有

**Comment by Array-Cats** [comment]
@EtherealAO 

今天再次复现，也是打开游戏后第一次进入JJC只有报错没有数据

![W6pmF.png](https://s1.328888.xyz/2022/06/05/W6pmF.png)

**Comment by Array-Cats** [comment]
@EtherealAO 

今天再次复现，打开游戏后打一遍JJC然后再打开URA后再次进入JJC后直接报错

其实昨天已经出现过一次的，不过就懒得截图了

![ztlXt.png](https://s1.328888.xyz/2022/06/07/ztlXt.png)

**Comment by EtherealAO** [comment]
想起来了，出问题的时候是不是有人的队伍不是15人队，如果是的话应该已经在[[#] 修复竞技场人数不满15时无法正常显示信息的BUG&&优化人数小于15时的显示](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/commit/ea20b9981f6c879fa73aebf99ec80862594283bf)修复了

**Comment by Array-Cats** [comment]
> 想起来了，出问题的时候是不是有人的队伍不是15人队，如果是的话应该已经在[[#] 修复竞技场人数不满15时无法正常显示信息的BUG&&优化人数小于15时的显示](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/commit/ea20b9981f6c879fa73aebf99ec80862594283bf)修复了

并不清楚，因为出错的时候队伍已经列出来了，我也不清楚三个队伍当中是否有小于15人（不过可以确认的是我的队伍是满人的）
