### ISSUE TITLE
更新数据文件的时候请不要进行自动判断/或在异常时尝试使用另一个地址

### ISSUE THREAD

**Issue by MirrorCubeSquare** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#51]
今天更新数据文件时出错，然后翻了一下源代码发现使用了
var isCN = RegionInfo.CurrentRegion.Name == "CN" || CultureInfo.CurrentUICulture.Name == "zh-CN";
来访问两个不同的资源地址
我认为在赛马娘本体是需要翻墙的现状下，自动判定是不可取的，并且github一直可用，另一个网站（相信是作者的个人网站）可用性未知
建议采用以下任何一种方法
1）更新数据的选项增加线路1（线路2）的提示
2）更新数据函数捕获异常，并在异常时尝试使用另一个线路（无论第一个选择如何）
3）提示让人手动在这里下载资源包（如果下载失败的话）

**Comment by EtherealAO** [comment]
> 并且github一直可用

[并非如此。](http://17ce.com/site/http/20220713_e6c8c130027c11edbe597947b4fa380d:1.html)

**Comment by EtherealAO** [comment]
[[+] 添加对更新服务器可用性的检测](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/commit/3abee2215e3d3fe13b3c296abc36c0ffbfff19a0)
