### ISSUE TITLE
开启程序时报错 如图

### ISSUE THREAD

**Issue by ocGuang** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#54]
![QQ图片20220721145139](https://user-images.githubusercontent.com/14138041/180148819-e3c66924-92dc-4df4-a6be-f380e3820d51.png)
请问这种情况怎么处理？

**Comment by EtherealAO** [comment]
试试[v1.9.2.5](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/releases/tag/v1.9.2.5)
