### ISSUE TITLE
有没有可能计算出偶像杯下一步会出现什么歌曲选项

### ISSUE THREAD

**Issue by kotoricon** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#60]
既然一般事件都能取到下一步会出现什么选项，不知道每次live前选歌部分能不能做到同样的事？
经常可能前一步刚点下去某个属性下一首歌直接卡住在某个属性上不够三首只能直接撕了，虽然要说也确实是个人的锅不过如果能优化下当然更好了

**Comment by EtherealAO** [comment]
很不幸，不可以
