### ISSUE TITLE
11.17版本更新后偶像杯育成中无法使用的问题

### ISSUE THREAD

**Issue by ShinodaKiyoshimo** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#61]
育成中没法看到支援卡刷新位置 但是在外面能正常看到种马胜鞍以及竞技场对手分数 请问这种情况应该怎么办 谢谢解答！
![image](https://user-images.githubusercontent.com/87769282/202407039-66abf399-eb8b-4e8d-9fc1-b3f827bb94af.png)

**Comment by EtherealAO** [comment]
单纯的忘记更新事件了，以后要是再忘可以去https://github.com/UmamusumeResponseAnalyzer/UmamusumeDeserializeDB5 自己编译一下然后覆盖到%localappdata%/UmamusumeResponseAnalyzer/里
