### ISSUE TITLE
模拟器中配置magisk后，ura启动后除了提示“已启动”外无任何输出。

### ISSUE THREAD

**Issue by lijiamu233** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#65]
运行结果如下（中间的ip地址是因为安装了Zerotier产生的）
![image](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/assets/21009615/45485c25-d576-44f1-bb0f-7652fd8e8680)

已知：在雷电模拟器中安装了magisk-delta并且安装了shamiko，LSPosed和UmamusumeLocalify三个模块，将MagiskHide中勾选了游戏本体，在Android/data/com.komoe.kumamusumegp目录下放置了config.json，里面的ip确认配置为本机ipconfig中的ipv4地址。
运行ura后通过netstat -aon | findstr "4693"，发现除了system外无任何进程在4693端口上，如下。
![image](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/assets/21009615/5a36e3a1-2276-4911-9be2-79114a054ca0)

**Comment by EtherealAO** [comment]
> 模块2.16及以后的config.json需要额外加一个dumpMsgPack，模板:
{"maxFps": 120,"dumpMsgPack":true,"packetNotifier": "http://192.168.1.184:4693"}
也可使用Kimjio的APP进行设置：https://github.com/Kimjio/umamusume-localify-android/releases/download/App_1.5.2/localify-settings-app-release-1.5.2.apk
请附带logcat信息
server进程是system，是HTTP.sys的正常表现
