### ISSUE TITLE
凯旋门赛后出错

### ISSUE THREAD

**Issue by onigumo3** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#75]
![QQ图片20231004211109](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/assets/146955847/9b10955f-d85e-47d9-8d03-39dd472cc47a)
![QQ图片20231004211113](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/assets/146955847/717a4254-1a9d-4f59-aab5-4d398960e392)
实际-5体力也会显示-20体力

**Comment by EtherealAO** [comment]
所有事件的详细数据均来源于kamigame，赛后事件这种每个剧本都可能效果不同的需要在https://github.com/UmamusumeResponseAnalyzer/UmamusumeDeserializeDB5/blob/master/Generator/SuccessEvent.cs#L146 单独添加。目前还没人做
