### ISSUE TITLE
问一下我开着这个程式打Apex会被封吗

### ISSUE THREAD

**Issue by LAMLITony** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#76]
问一下我开着这个程式打Apex会被封吗

**Comment by EtherealAO** [comment]
据我所知，不特别指向Apex但仍会被EAC检测到的只有大漠系的脚本。
URA本体没有任何特征，除非你手贱把ura-core等dll扔到APEX目录下，不然不可能会被封
