### ISSUE TITLE
I'd like to use this app with unlockSize and toggle fullscreen function

### ISSUE THREAD

**Issue by N4SH1** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#95]
I used to use [this app](https://kizuna.uma.bet/) but now that it is no longer updated so I'm using UmamusumeResponseAnalyzer right now.
I would like the feature to toggle fullscreen and window with F11 and the unlockSize feature that was available in Kizuna.

**Comment by EtherealAO** [comment]
https://github.com/UmamusumeResponseAnalyzer/ura-core
The ura-core only provides the most basic functions necessary for running URA (and unlocking FPS), and it has a compatibility mode: you only need to rename it to winhttp.dll to use it with other mods (unless they are also using this file name).

**Comment by N4SH1** [comment]
It worked out perfectly thanks to your advice.
Thank you for taking the time to answer my questions.
I'll continue to support this app!
