### ISSUE TITLE
需要日语翻译

### ISSUE THREAD

**Issue by Nekomanta0829** [UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer#96]
感谢您开发这个精彩的 Uma Musume 工具。 我想使用它，但我想用日语而不是中文。 有什么办法可以改变语言吗？ 如果没有的话，你能为我做一个吗？
我是日本用户，不会说中文，所以我使用谷歌翻译创建了这个。很抱歉句子不正确。

**Comment by EtherealAO** [comment]
I saw your request in the discussion and i'm working on it.
I've updated internationalization at [更新I18N](https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/commit/1bd69b1ff5fe2557ce7562b07a53d1e836a54b15) with gpt4.0 translation, but quality in Japanese is very low, so you may use English instead until someone do it.
If you urgently need it you can clone this repo and build by yourself, it changed too many codes so I have to test it for a period before release.

**Comment by EtherealAO** [comment]
It seems works fine, you can download it from https://github.com/UmamusumeResponseAnalyzer/UmamusumeResponseAnalyzer/releases/tag/v1.13.2.1 .
As it's designed with Chinese, it's has some layout issue, I will update per language layout on next release.

**Comment by Nekomanta0829** [comment]
我安装了它，它可以用日语运行。
这非常有帮助，谢谢！
